/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
if(!window.Typekit)window.Typekit={};window.Typekit.config={"a":"709114","c":[".box-link,.widget-area h3","\"alternate-gothic-no-1-d\",helvetica,arial,sans-serif"],"f":"//use.typekit.net/c/73c50d/1w;alternate-gothic-no-1-d,1,TV3:H:n4/{format}{/extras*}?3bb2a6e53c9684ffdc9a9aff135b2a629c74e59eae32629bb0e34561bfc9fa96965126b9fc67cd5bf3930672feedb13f9acae6b788dce2bacf2fbb869e668858e74b47b17a1d97eba9e3e9a29564d33a273e1cea25256ed87665e51a5b081503c978f7","fi":[10326],"fn":["alternate-gothic-no-1-d",["n4"]],"ht":"tk","js":"1.4.3","k":"//use.typekit.net/{id}.js","kt":"fqa3ulw","p":"//p.typekit.net/p.gif?s=1&k=fqa3ulw&ht=tk&h={host}&f=10326&a=709114&_={_}","ps":1,"w":"fqa3ulw"};
/*{"k":"1.4.3","auto_updating":false}*/
/*{"created":"2013-03-27T16:19:47Z","k":"1.4.3"}*/
;(function(window,document,undefined){
var g=void 0,k=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var aa=this;function ba(a,c){var b=a.split("."),e=aa;!(b[0]in e)&&e.execScript&&e.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)!b.length&&c!==g?e[d]=c:e=e[d]?e[d]:e[d]={}}aa.cb=k;function ca(a,c,b){return a.call.apply(a.bind,arguments)}
function da(a,c,b){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,e);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function p(a,c,b){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return p.apply(l,arguments)}var ea=Date.now||function(){return+new Date};
function q(a,c){this.Sa=a;this.ua=c||a;this.j=this.ua.document;this.B=g}q.prototype.createElement=function(a,c,b){a=this.j.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?this.fa(a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.j.createTextNode(b));return a};function r(a,c,b){a=a.j.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function ha(a){function c(){document.body?a():setTimeout(c,0)}c()}
function t(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function u(a,c){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ia(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return k;return m}
q.prototype.fa=function(a,c){this.ca()?a.setAttribute("style",c):a.style.cssText=c};q.prototype.ca=function(){if(this.B===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.B=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.B};function w(a,c,b){this.jb=a;this.Ba=c;this.bb=b}ba("internalWebfont.BrowserInfo",w);function x(a,c,b,e,d,f,h,j){this.ea=a;this.ab=c;this.Ga=b;this.Fa=e;this.Wa=d;this.Va=f;this.Ea=h;this.u=j}
ba("internalWebfont.UserAgent",x);x.prototype.getName=n("ea");x.prototype.getName=x.prototype.getName;x.prototype.getVersion=n("ab");x.prototype.getVersion=x.prototype.getVersion;x.prototype.getEngine=n("Ga");x.prototype.getEngine=x.prototype.getEngine;x.prototype.getEngineVersion=n("Fa");x.prototype.getEngineVersion=x.prototype.getEngineVersion;x.prototype.getPlatform=n("Wa");x.prototype.getPlatform=x.prototype.getPlatform;x.prototype.getPlatformVersion=n("Va");x.prototype.getPlatformVersion=x.prototype.getPlatformVersion;
x.prototype.getDocumentMode=n("Ea");x.prototype.getDocumentMode=x.prototype.getDocumentMode;x.prototype.Ka=n("u");x.prototype.getBrowserInfo=x.prototype.Ka;function ja(a,c){this.e=a;this.v=c}var ka=new x("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g,new w(m,m,m));
ja.prototype.parse=function(){var a;if(-1!=this.e.indexOf("MSIE")){a=y(this);var c=A(this),b=B(this.e,/(MSIE [\d\w\.]+)/,1);if(""!=b){var e=b.split(" "),b=e[0],e=e[1],d=C(e),f=C(c);a=new x(b,e,b,e,a,c,D(this.v),new w("Windows"==a&&6<=d.l||"Windows Phone"==a&&8<=f.l,m,m))}else a=new x("MSIE","Unknown","MSIE","Unknown",a,c,D(this.v),new w(m,m,m))}else if(-1!=this.e.indexOf("Opera"))a=la(this);else if(/AppleWeb(K|k)it/.test(this.e)){a=y(this);var c=A(this),b=B(this.e,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,
1),h=m;""==b&&(b="Unknown");e=C(b);h=C(c);d="Unknown";-1!=this.e.indexOf("Chrome")||-1!=this.e.indexOf("CrMo")||-1!=this.e.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(this.e)?d="Silk":"BlackBerry"==a||"Android"==a?d="BuiltinBrowser":-1!=this.e.indexOf("Safari")?d="Safari":-1!=this.e.indexOf("AdobeAIR")&&(d="AdobeAIR");f="Unknown";"BuiltinBrowser"==d?f="Unknown":/Silk\/\d/.test(this.e)?f=B(this.e,/Silk\/([\d\._]+)/,1):-1!=this.e.indexOf("Version/")?f=B(this.e,/Version\/([\d\.\w]+)/,1):"Chrome"==d?
f=B(this.e,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==d&&(f=B(this.e,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(h=C(f),h=2<h.l||2==h.l&&5<=h.A):h="BlackBerry"==a?10<=h.l:"Android"==a?2<h.l||2==h.l&&1<h.A:526<=e.l||525<=e.l&&13<=e.A;a=new x(d,f,"AppleWebKit",b,a,c,D(this.v),new w(h,536>e.l||536==e.l&&11>e.A,"iPhone"==a||"iPad"==a||"iPod"==a||"Macintosh"==a))}else-1!=this.e.indexOf("Gecko")?(c=a="Unknown",b=m,-1!=this.e.indexOf("Firefox")?(a="Firefox",e=B(this.e,/Firefox\/([\d\w\.]+)/,1),""!=e&&
(b=C(e),c=e,b=3<=b.l&&5<=b.A)):-1!=this.e.indexOf("Mozilla")&&(a="Mozilla"),e=B(this.e,/rv:([^\)]+)/,1),""==e?e="Unknown":b||(b=C(e),b=1<b.l||1==b.l&&9<b.A||1==b.l&&9==b.A&&2<=b.Ua||e.match(/1\.9\.1b[123]/)!=l||e.match(/1\.9\.1\.[\d\.]+/)!=l),a=new x(a,c,"Gecko",e,y(this),A(this),D(this.v),new w(b,m,m))):a=ka;return a};
function y(a){var c=B(a.e,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=B(a.e,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function A(a){var c=B(a.e,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);return c||(c=B(a.e,/Windows Phone( OS)? ([^;)]+)/,2))||(c=B(a.e,/(iPhone )?OS ([\d_]+)/,2))||(c=B(a.e,/Linux ([i\d]+)/,1))?c:(a=B(a.e,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function la(a){var c="Unknown",b="Unknown",e=B(a.e,/(Presto\/[\d\w\.]+)/,1);""!=e?(b=e.split("/"),c=b[0],b=b[1]):(-1!=a.e.indexOf("Gecko")&&(c="Gecko"),e=B(a.e,/rv:([^\)]+)/,1),""!=e&&(b=e));if(-1!=a.e.indexOf("Opera Mini/"))return e=B(a.e,/Opera Mini\/([\d\.]+)/,1),""==e&&(e="Unknown"),new x("OperaMini",e,c,b,y(a),A(a),D(a.v),new w(m,m,m));if(-1!=a.e.indexOf("Version/")){var d=B(a.e,/Version\/([\d\.]+)/,1);if(""!=d)return e=C(d),new x("Opera",d,c,b,y(a),A(a),D(a.v),new w(10<=e.l,m,m))}d=B(a.e,/Opera[\/ ]([\d\.]+)/,
1);return""!=d?(e=C(d),new x("Opera",d,c,b,y(a),A(a),D(a.v),new w(10<=e.l,m,m))):new x("Opera","Unknown",c,b,y(a),A(a),D(a.v),new w(m,m,m))}function C(a){a=/([0-9]+)(?:\.([0-9]+)(?:\.([0-9]+)?)?)?/.exec(a);var c={};a&&(c.l=parseInt(a[1]||-1,10),c.A=parseInt(a[2]||-1,10),c.Ua=parseInt(a[3]||-1,10));return c}function B(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}function D(a){if(a.documentMode)return a.documentMode}function ma(a){this.Qa=a||"-"}
ma.prototype.h=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Qa)};function na(a,c,b){this.g=a;this.m=c;this.ma=b;this.q="wf";this.n=new ma("-")}function G(a){u(a.m,a.n.h(a.q,"loading"));ia(a.m,a.n.h(a.q,"active"))||t(a.m,a.n.h(a.q,"inactive"));H(a,"inactive")}function H(a,c,b,e){if(a.ma[c])a.ma[c](b,e)}function oa(a,c){this.width=a;this.height=c}function pa(){this.za="'"}
pa.prototype.quote=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push(this.za+e+this.za)}return c.join(",")};function qa(){this.xa=ra;this.P=sa}var ra=["font-style","font-weight"],sa={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function ta(a,c,b){this.Pa=a;this.Xa=c;this.P=b}ta.prototype.expand=function(a,c){for(var b=0;b<this.P.length;b++)if(c==this.P[b][0]){a[this.Pa]=this.Xa+":"+this.P[b][1];break}};qa.prototype.expand=function(a){if(2!=a.length)return l;for(var c=[l,l],b=0,e=this.xa.length;b<e;b++){var d=this.xa[b];(new ta(b,d,this.P[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":l};function I(a,c){this.g=a;this.M=c;this.Ta=new pa;this.Ja=new qa;this.I=this.g.createElement("span",{},this.M)}
function ua(a,c,b){b=b?a.Ja.expand(b):"";c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.Ta.quote(c)+";"+b;a.g.fa(a.I,c)}function va(a){r(a.g,"body",a.I)}function wa(a){return new oa(a.I.offsetWidth,a.I.offsetHeight)}I.prototype.remove=function(){var a=this.I;a.parentNode&&a.parentNode.removeChild(a)};
function xa(a,c,b,e,d,f,h,j,s){this.ha=a;this.Oa=c;this.g=b;this.S=e;this.R=d;this.M=s||"BESbswy";this.u=f;this.z={};this.ga=h||5E3;this.va=j||l;this.L=this.K=l;a=new I(this.g,this.M);va(a);for(var z in J)J.hasOwnProperty(z)&&(ua(a,J[z],this.R),this.z[J[z]]=wa(a));a.remove()}var J={hb:"serif",gb:"sans-serif",fb:"monospace",eb:"Apple Color Emoji"};
xa.prototype.start=function(){this.K=new I(this.g,this.M);va(this.K);this.L=new I(this.g,this.M);va(this.L);this.Za=ea();ua(this.K,this.S+",serif",this.R);ua(this.L,this.S+",sans-serif",this.R);ya(this)};function K(a,c,b){return a.u.bb?!!a.z[b]&&c.width==a.z[b].width:!!a.z[b]&&c.width==a.z[b].width&&!!a.z[b]&&c.height==a.z[b].height}function za(a,c,b){for(var e in J)if(J.hasOwnProperty(e)&&K(a,c,J[e])&&K(a,b,J[e]))return k;return m}
function ya(a){var c=wa(a.K),b=wa(a.L);K(a,c,"serif")&&K(a,b,"sans-serif")||a.u.Ba&&za(a,c,b)?ea()-a.Za>=a.ga?a.u.Ba&&za(a,c,b)&&(a.va===l||a.va.hasOwnProperty(a.S))?Aa(a,a.ha):Aa(a,a.Oa):setTimeout(p(function(){ya(this)},a),25):Aa(a,a.ha)}function Aa(a,c){a.K.remove();a.L.remove();c(a.S,a.R)}function L(a,c,b,e){this.g=c;this.C=b;this.$=0;this.Aa=this.ra=m;this.ga=e;this.u=a.u}
L.prototype.watch=function(a,c,b,e,d){var f=a.length;if(0===f)G(this.C);else{for(var h=0;h<f;h++){var j=a[h];c[j]||(c[j]=["n4"]);this.$+=c[j].length}d&&(this.ra=d);for(h=0;h<f;h++){j=a[h];d=c[j];for(var s=b[j],z=0,E=d.length;z<E;z++){var W=d[z],v=this.C,F=j,P=W;t(v.m,v.n.h(v.q,F,P,"loading"));H(v,"fontloading",F,P);v=p(this.Ha,this);F=p(this.Ia,this);(new e(v,F,this.g,j,W,this.u,this.ga,l,s)).start()}}}};
L.prototype.Ha=function(a,c){var b=this.C;u(b.m,b.n.h(b.q,a,c,"loading"));u(b.m,b.n.h(b.q,a,c,"inactive"));t(b.m,b.n.h(b.q,a,c,"active"));H(b,"fontactive",a,c);this.Aa=k;Ba(this)};L.prototype.Ia=function(a,c){var b=this.C;u(b.m,b.n.h(b.q,a,c,"loading"));ia(b.m,b.n.h(b.q,a,c,"active"))||t(b.m,b.n.h(b.q,a,c,"inactive"));H(b,"fontinactive",a,c);Ba(this)};
function Ba(a){0==--a.$&&a.ra&&(a.Aa?(a=a.C,u(a.m,a.n.h(a.q,"loading")),u(a.m,a.n.h(a.q,"inactive")),t(a.m,a.n.h(a.q,"active")),H(a,"active")):G(a.C))}function M(a,c){this.Sa=a;this.ua=c||a;this.j=document;this.B=g}M.prototype=q.prototype;function N(a){return"https:"==a.j.location.protocol}M.prototype.La=function(){return this.j.location.hostname};
function Ca(a,c,b){var e=a.j.getElementsByTagName("head")[0];if(e){var d=a.j.createElement("script");d.src=c;var f=m;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=k,b&&b(),d.onload=d.onreadystatechange=l,"HEAD"==d.parentNode.tagName&&e.removeChild(d)};e.appendChild(d)}}M.prototype.fa=function(a,c){this.ca()?a.setAttribute("style",c):a.style.cssText=c};
M.prototype.ca=function(){if(this.B===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.B=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.B};function Da(){var a=[{name:"font-family",value:O.c[i+1]}];this.Ya=[O.c[i]];this.na=a}function Ea(a){for(var c=a.Ya.join(","),b=[],e=0;e<a.na.length;e++){var d=a.na[e];b.push(d.name+":"+d.value+";")}return c+"{"+b.join("")+"}"}
function Fa(a,c,b,e){this.J=a;this.T=c;this.Ma=b;this.ib=e;this.pa={};this.oa={}}Fa.prototype.D=function(a){return a?(this.pa[a.U]||this.T).slice(0):this.T.slice(0)};Fa.prototype.watch=function(a,c,b){var e=[],d={};Ga(this,c,e,d);a(e,d,b)};function Ga(a,c,b,e){b.push(a.J);e[a.J]=a.D(c);a=a.oa[c.U]||[];for(c=0;c<a.length;c++){for(var d=a[c],f=d.J,h=m,j=0;j<b.length;j++)b[j]==f&&(h=k);h||(b.push(f),e[f]=d.D())}}function Ha(a,c){this.J=a;this.T=c}Ha.prototype.D=n("T");
function Q(a,c,b){this.Ma=a;this.U=c;this.qa=b}function Ia(){this.ka=this.Da=this.r=this.N=this.O=k}function R(a){Ja.X.push(a)}function S(a){this.g=a;this.la=this.t=this.e=this.W=l;this.o=[];this.Q=[];this.Ca=this.aa=this.Y=this.Z=l}
function Ka(a,c){a.e=c;if(a.W){var b;a:{b=a.W;for(var e=a.e,d=a.la,f=0;f<b.X.length;f++){var h=b.X[f],j=e,s=d;s||(s=new Ia);if(h.qa&&h.qa(j.getName(),j.getVersion(),j.getEngine(),j.getEngineVersion(),j.getPlatform(),j.getPlatformVersion(),j.getDocumentMode(),s)){b=h;break a}}b=l}a.t=b}}S.prototype.supportsConfiguredBrowser=function(){return!!this.t};
S.prototype.init=function(){if(0<this.Q.length){for(var a=[],c=0;c<this.Q.length;c++)a.push(Ea(this.Q[c]));var c=this.g,a=a.join(""),b=this.g.j.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));r(c,"head",b)}};
S.prototype.load=function(a,c){var b=this.t.U;if(this.aa){var e;e=this.aa;var d=e.G[b];e=d?La(e,d):l;for(d=0;d<this.o.length;d++){for(var f=this.o[d],h=this.t,j=e,s=[],z=f.J.split(",")[0].replace(/"|'/g,""),E=f.D(),W=s,v=g,F=[],P={},fa=0;fa<E.length;fa++)v=E[fa],0<v.length&&!P[v]&&(P[v]=k,F.push(v));E=F;j=j.ya?j.ya(z,E,W):E;h=h.U;f.pa[h]=j;f.oa[h]=s}}if(this.Z){e=[];if(this.Y){e=new Ma(this.g,this.t,this.o);d=[];f=this.Y.H[b]||[];for(s=0;s<f.length;s++){a:switch(f[s]){case "observeddomain":h=new Na(e.g);
break a;case "fontmask":h=new Oa(e.t,e.o);break a;default:h=l}h&&d.push(h)}e=d}d=[];for(f=0;f<e.length;f++)d.push(e[f].toString());b=this.Z.h(N(this.g),{format:b,extras:d});r(this.g,"head",this.g.createElement("link",{rel:"stylesheet",href:b}))}if(a){var ga=this,gb=this.t;ha(function(){for(var b=0;b<ga.o.length;b++)ga.o[b].watch(a,gb,c&&b==ga.o.length-1)})}};S.prototype.collectFontFamilies=function(a,c){for(var b=0;b<this.o.length;b++)Ga(this.o[b],this.t,a,c)};
S.prototype.performOptionalActions=function(){if(this.da){var a=this,c=this.e,b=this.g;ha(function(){var e=a.da;if(e.wa){var d=window.__adobewebfontsappname__,d=d?d.toString().substr(0,20):"",e=e.wa.h(N(b),{host:encodeURIComponent(b.j.location.hostname),app:encodeURIComponent(d),_:(+new Date).toString()}),f=new Image(1,1);f.src=e;f.onload=function(){f.onload=l}}e=a.da;e.ja&&(e=e.ja.h(c,b),r(b,"body",e))})}};function Pa(a,c,b,e,d){this.Ra=a;this.g=c;this.e=b;this.m=e;this.ia=d;this.s=[]}
Pa.prototype.V=function(a){this.s.push(a)};Pa.prototype.load=function(a,c){var b=a,e=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)e=b||{},b=[];if(b.length)for(var d=this,f=b.length,h=0;h<b.length;h++){var j=this.Ra.h(N(this.g),{id:encodeURIComponent(b[h])});Ca(this.g,j,function(){0==--f&&Qa(d,e)})}else Qa(this,e)};
function Qa(a,c){if(0!=a.s.length){for(var b=new na(a.g,a.m,c),e=m,d=0;d<a.s.length;d++)a.s[d].init(),e=e||a.s[d].supportsConfiguredBrowser();if(e){t(b.m,b.n.h(b.q,"loading"));H(b,"loading");for(var f=new L(a.e,a.g,b),b=function(a,b,c){f.watch(a,b,{},xa,c)},e=0;e<a.s.length;e++)d=a.s[e],d.supportsConfiguredBrowser()&&(d.load(b,e==a.s.length-1),d.performOptionalActions(window))}else G(b);a.s=[]}}function Ra(a,c){this.F=a;this.ia=c;this.s=[]}Ra.prototype.V=function(a){this.s.push(a)};
Ra.prototype.load=function(){var a=this.F.__webfonttypekitmodule__;if(a)for(var c=0;c<this.s.length;c++){var b=this.s[c],e=a[b.Ca];if(e){var d=this.ia;e(function(a,c,e){c=[];var s={};Ka(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(l,d),b.collectFontFamilies(c,s),b.performOptionalActions(window));e(b.supportsConfiguredBrowser(),c,s)})}}};function Sa(a,c){this.ea=a;this.ya=c}Sa.prototype.getName=n("ea");function Ta(a){var c=T;La(c,a.getName())||c.ba.push(a)}
function La(a,c){for(var b=0;b<a.ba.length;b++){var e=a.ba[b];if(c===e.getName())return e}return l}function Ma(a,c,b){this.g=a;this.t=c;this.o=b}function Na(a){this.g=a}Na.prototype.toString=function(){return encodeURIComponent(this.g.La?this.g.j.location.hostname:document.location.hostname)};function Oa(a,c){this.t=a;this.o=c}
Oa.prototype.toString=function(){for(var a=[],c=0;c<this.o.length;c++)for(var b=this.o[c],e=b.D(),b=b.D(this.t),d=0;d<e.length;d++){var f;a:{for(f=0;f<b.length;f++)if(e[d]===b[f]){f=k;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(e=a.length;0<e;e-=4)b=a.slice(0>e-4?0:e-4,e),c.unshift(parseInt(b,2).toString(16));return c.join("")};function U(a){this.$a=a}
U.prototype.h=function(a,c){var b=c||{},e=this.$a.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,e){return e&&b[c]?"/"+b[c].join("/"):b[c]||""});e.match(/^\/\//)&&(e=(a?"https:":"http:")+e);return e.replace(/\/*\?*($|\?)/,"$1")};function Ua(a,c,b,e){this.F=a;this.j=c;this.Na=b;this.ta=e}
Ua.prototype.h=function(a,c){var b=this.j.createElement("img");b.setAttribute("width",62);b.setAttribute("height",25);b.setAttribute("src",this.Na.h(N(c)));b.setAttribute("class","typekit-badge");b.setAttribute("alt","Fonts by Typekit");b.setAttribute("title","Information about the fonts used on this site");b.style.position="fixed";b.style.zIndex=2E9;b.style.right=0;b.style.bottom=0;b.style.cursor="pointer";b.style.border=0;"Opera"!=a.getName()&&(b.style.content="none");b.style.display="inline";b.style["float"]=
"none";b.style.height="25px";b.style.left="auto";b.style.margin=0;b.style.maxHeight="25px";b.style.maxWidth="62px";b.style.minHeight="25px";b.style.minWidth="62px";b.style.orphans=2;b.style.outline="none";b.style.overflow="visible";b.style.padding=0;b.style.pageBreakAfter="auto";b.style.pageBreakBefore="auto";b.style.pageBreakInside="auto";b.style.tableLayout="auto";b.style.textIndent=0;b.style.top="auto";b.style.unicodeBidi="normal";b.style.verticalAlign="baseline";b.style.visibility="visible";b.style.widows=
2;b.style.width="65px";if(this.ta){var e=this.j,d=this.ta;Va(this,b,"click",function(){e.location.href=d})}var f=a.getPlatform();if("MSIE"==a.getName()&&"Windows Phone"!=f){b.style.position="absolute";var h=this,j=function(){var a=Wa(h,"scrollLeft","scrollTop"),c=Wa(h,"clientWidth","clientHeight");b.style.bottom="auto";b.style.right="auto";b.style.top=a[1]+c[1]-25+"px";b.style.left=a[0]+c[0]-3-62+"px"};Va(this,this.F,"scroll",j);Va(this,this.F,"resize",j)}if("iPhone"==f||"iPod"==f||"iPad"==f||"Android"==
f||"Windows Phone"==f||"BlackBerry"==f)b.style.display="none";return b};function Wa(a,c,b){var e=0,d=0;a=a.j;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b]))e=a.documentElement[c],d=a.documentElement[b];else if(a.body&&(a.body[c]||a.body[b]))e=a.body[c],d=a.body[b];return[e,d]}function Va(a,c,b,e){if(c.attachEvent){var d=a.F;c["e"+b+e]=e;c[b+e]=function(){c["e"+b+e](d.event)};c.attachEvent("on"+b,c[b+e])}else c.addEventListener(b,e,m)}var Ja=new function(){this.X=[]};
R(new Q("air-linux-win","a",function(a,c,b,e,d,f){if(b=m||("Windows"==d&&"Unknown"==f?k:m)||("Ubuntu"==d||"Linux"==d?k:m))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
R(new Q("air-osx","b",function(a,c,b,e,d,f){if(!(b=m))b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m;if(b)a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
R(new Q("builtin-android2to3-android4plus","a",function(a,c,b,e,d,f,h,j){if(!(c=m))b=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=2==c&&2<=b||3==c&&1>b):c=m;c||(f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),j=parseInt(f[2],10),c=4==d&&1<=j||4<d):c=m);return!c?m:"BuiltinBrowser"==a}));
R(new Q("builtin-android3to4","f",function(a,c,b,e,d,f,h,j){if(!(c=m))f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),j=parseInt(f[2],10),c=3==d&&1<=j||4==d&&1>j):c=m;return!c?m:"BuiltinBrowser"==a}));R(new Q("builtin-bb10plus","d",function(a,c,b,e,d,f,h,j){c=m||j.ka&&10<=parseInt(f,10);return!c?m:"BuiltinBrowser"==a}));
R(new Q("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[3],10),b=10<f||10==f&&4<=b):b="Macintosh"==d&&"Unknown"==f?k:m);if(b=b||("Ubuntu"==d||"Linux"==d?k:m))a:{if("Chrome"==
a&&(d=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c)))if(a=parseFloat(d[1]),c=parseInt(d[2],10),d=parseInt(d[3],10),!(6<=a)&&(4<a||4==a&&249<c||4==a&&249==c&&4<=d)){a=k;break a}a=m}else a=m;return a}));
R(new Q("chrome6plus-androidany-chromeos-ipad5plus-iphone5plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(e=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[3],10),b=10<b||10==b&&4<=e):b="Macintosh"==d&&"Unknown"==f?k:
m);b=(b=(b=b||("Ubuntu"==d||"Linux"==d?k:m))||j.r&&"Android"==d)||"CrOS"==d;b||(b=j.N&&"iPad"==d?(b=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(b[1],10):m:m);b||(b=j.O&&("iPhone"==d||"iPod"==d)?(d=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(d[1],10):m:m);if(b)a:{if("Chrome"==a&&(a=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c))&&6<=parseFloat(a[1])){a=k;break a}a=g}else a=m;return a}));
R(new Q("chrome6plus-ipad4-iphone4","a",function(a,c,b,e,d,f,h,j){if(!(b=m))a:{if(j.N&&"iPad"==d&&(b=/^([0-9]+)_([0-9]+)/.exec(f))){e=parseInt(b[2],10);b=4==parseInt(b[1],10)&&2<=e;break a}b=m}if(!b)a:{if(j.O&&("iPhone"==d||"iPod"==d))if(d=/^([0-9]+)_([0-9]+)/.exec(f)){f=parseInt(d[2],10);b=4==parseInt(d[1],10)&&2<=f;break a}b=m}if(b)a:{if("Chrome"==a&&(a=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c))&&6<=parseFloat(a[1])){a=k;break a}a=g}else a=m;return a}));
R(new Q("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){a=(a=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);a||(a=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&a?(f=parseInt(a[1],10),a=parseInt(a[2],10),a=6<f||6==f&&1<=a):a=m);(a=a||("Ubuntu"==d||"Linux"==d?k:m))?"Gecko"==b?(b=/1.9.1b[1-3]{1}/,e=/1.9.1/.test(e)&&!b.test(e)):e=m:e=m;return e}));
R(new Q("ff35-osx","b",function(a,c,b,e,d,f){if(!(a=m))a=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),a=10<d||10==d&&4<=f):a="Macintosh"==d&&"Unknown"==f?k:m;a?"Gecko"==b?(b=/1.9.1b[1-3]{1}/,e=/1.9.1/.test(e)&&!b.test(e)):e=m:e=m;return e}));
R(new Q("ff36plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){a=(a=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);a||(c=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&c?(a=parseInt(c[1],10),c=parseInt(c[2],10),a=6<a||6==a&&1<=c):a=m);a||(a=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&a?(f=parseInt(a[1],10),a=parseInt(a[3],10),a=10<f||10==f&&4<=a):a="Macintosh"==d&&"Unknown"==f?k:m);if(a=(a=a||("Ubuntu"==d||"Linux"==
d?k:m))||j.r&&"Android"==d)a:{if("Gecko"==b&&(e=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))){b=parseFloat(e[1]);e=parseInt(e[3],10);b=1.9<b||1.9<=b&&1<e;break a}b=m}else b=m;return b}));
R(new Q("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,c,b,e,d,f,h){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(f=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),b=6<d||6==d&&1<=f):b=m);h=b?"MSIE"==a?(a=/([0-9]+.[0-9]+)/.exec(c))?6<=parseFloat(a[1])&&(h===g||9>h):m:g:m;return h}));
R(new Q("ie9plus-win7plus-winvista","d",function(a,c,b,e,d,f,h){if(!(c=m))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=m;a=(d=c||("Windows"==d&&"6.0"==f?k:m))?"MSIE"==a?9<=h:g:m;return a}));R(new Q("ieany-winphone8plus","d",function(a,c,b,e,d,f,h,j){if(!(c=m))f=/^([0-9]+)/.exec(f),c=j.Da&&"Windows Phone"==d&&f?8<=parseInt(f[1],10):m;return!c?m:"MSIE"==a}));
R(new Q("opera10-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[2],10),b=6<f||6==f&&1<=b):b=m);(b=b||("Ubuntu"==d||"Linux"==d?k:m))?"Opera"==a?(a=parseFloat(c),a=10.54<=a&&11.1>a):a=m:a=m;return a}));
R(new Q("opera10-osx","b",function(a,c,b,e,d,f){if(!(b=m))b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m;b?"Opera"==a?(a=parseFloat(c),a=10.54<=a&&11.1>a):a=m:a=m;return a}));
R(new Q("opera11plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[3],10),b=10<f||10==f&&4<=b):b="Macintosh"==d&&"Unknown"==f?k:m);b=(b=b||("Ubuntu"==d||"Linux"==
d?k:m))||j.r&&"Android"==d;return!b?m:"Opera"==a?11.1<=parseFloat(c):m}));R(new Q("safari3to5-osx","b",function(a,c,b,e,d,f){if(!(c=m))c=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&c?(d=parseInt(c[1],10),f=parseInt(c[3],10),c=10<d||10==d&&4<=f):c="Macintosh"==d&&"Unknown"==f?k:m;if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&(a=/([0-9]+.[0-9]+)/.exec(e))){a=parseFloat(a[1]);a=525.13<=a&&534.5>a;break a}a=m}else a=m;return a}));
R(new Q("safari3to5-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){c=(c=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);c||(f=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),c=6<d||6==d&&1<=f):c=m);if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&(a=/([0-9]+.[0-9]+)/.exec(e))){a=parseFloat(a[1]);a=525.13<=a&&534.5>a;break a}a=m}else a=m;return a}));
R(new Q("safari5plus-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f){c=(c=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);if(!c){var h=/^([0-9]+).([0-9]+)/.exec(f);"Windows"==d&&h?(c=parseInt(h[1],10),h=parseInt(h[2],10),c=6<c||6==c&&1<=h):c=m}c||(c=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&c?(d=parseInt(c[1],10),f=parseInt(c[3],10),c=10<d||10==d&&4<=f):c="Macintosh"==d&&"Unknown"==f?k:m);if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&
(a=/([0-9]+.[0-9]+)/.exec(e))){a=534.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
R(new Q("safariany-ipad4-iphone4","a",function(a,c,b,e,d,f,h,j){if(!(c=m))a:{if(j.N&&"iPad"==d&&(c=/^([0-9]+)_([0-9]+)/.exec(f))){e=parseInt(c[2],10);c=4==parseInt(c[1],10)&&2<=e;break a}c=m}if(!c)a:{if(j.O&&("iPhone"==d||"iPod"==d))if(f=/^([0-9]+)_([0-9]+)/.exec(f)){j=parseInt(f[2],10);c=4==parseInt(f[1],10)&&2<=j;break a}c=m}return!c?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));
R(new Q("safariany-ipad5plus-iphone5plus","d",function(a,c,b,e,d,f,h,j){if(!(c=m))c=j.N&&"iPad"==d?(c=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(c[1],10):m:m;c||(c=j.O&&("iPhone"==d||"iPod"==d)?(f=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(f[1],10):m:m);return!c?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));
R(new Q("silk1to2-android2to3-osx","a",function(a,c,b,e,d,f,h,j){if(!(b=m))e=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=2==b&&2<=e||3==b&&1>e):b=m;b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m);return!b?m:j.r&&"Silk"==a?2>parseInt(c,10):m}));
R(new Q("silk2plus-android3to4-linux","f",function(a,c,b,e,d,f,h,j){if(!(b=m))b=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[2],10),b=3==f&&1<=b||4==f&&1>b):b=m;d=b||("Ubuntu"==d||"Linux"==d?k:m);return!d?m:j.r&&"Silk"==a?2<=parseInt(c,10):m}));
R(new Q("silk2plus-android4plus","a",function(a,c,b,e,d,f,h,j){if(!(b=m))f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),b=4==d&&1<=f||4<d):b=m;return!b?m:j.r&&"Silk"==a?2<=parseInt(c,10):m}));var T=new function(){this.ba=[];this.G={}};Ta(new Sa("AllFonts",function(a,c){return c}));
Ta(new Sa("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var e=0;e<c.length;e++){var d=c[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;b.push(new Ha(f,[d]))}a={};for(d=0;d<c.length;d++)b=c[d],e=b.charAt(1),(a[e]||(a[e]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;h++){var j=f[h];if(a[j]){e=e.concat(a[j]);break}}b=e;e={};a=[];for(d=0;d<b.length;d++)f=b[d],e[f]||(e[f]=k,a.push(f));b=[];for(e=0;e<c.length;e++){d=c[e];
for(f=0;f<a.length;f++)h=a[f],h==d&&b.push(h)}return b}));T.G.a="AllFonts";T.G.b="AllFonts";T.G.d="AllFonts";T.G.f="AllFonts";T.G.i="DefaultFourFontsWithSingleFvdFamilies";var V=new function(){this.H={}};V.H.a=[];V.H.b=[];V.H.d=[];V.H.f=["observeddomain"];V.H.i=["observeddomain","fontmask"];var Xa=(new ja(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ya=window.Typekit.config||{},Za=l;Ya.k&&(Za=new U(Ya.k));var $a=function(a,c){setTimeout(a,c)},X=new Pa(Za,new M(window),Xa,document.documentElement,$a),Y=new Ra(window,$a);window.Typekit.load=function(){X.load.apply(X,arguments)};window.Typekit.addKit=function(){X.V.apply(X,arguments)}}var ab,bb=l,cb=l,db=l,eb,Z,$,O=window.Typekit.config||{};O.b&&(bb=new U(O.b),cb=new Ua(window,document,bb,O.bu));O.p&&(db=new U(O.p));eb=new function(){var a=db;this.ja=cb;this.wa=a};
$=new S(new M(window));$.da=eb;Z=new Ia;Z.O=!O.si;Z.N=!O.st;Z.r=!O.sa;Z.Da=!O.sw;Z.ka=!O.sb;$.la=Z;O.w&&($.Ca=O.w);O.f&&(ab=new U(O.f),$.Z=ab);var i;if(O.fn)for(i=0;i<O.fn.length;i+=2)$.o.push(new Fa(O.fn[i],O.fn[i+1]));if(O.c)for(i=0;i<O.c.length;i+=2)$.Q.push(new Da);$.Y=V;$.W=Ja;$.aa=T;var fb;if(fb=Y)fb=!!Y.F.__webfonttypekitmodule__;fb?(Y.V($),Y.load()):(Ka($,Xa),window.Typekit.addKit($));
})(this,document);
